In [12]:
import tvm
import numpy as np

In [13]:
f = tvm._ffi.get_global_func("tvm.contrib.mlas.gemm_packb")

In [21]:
a = tvm.nd.array(np.random.random([100,100]).astype("float32"))
b = tvm.nd.array(np.random.random([11200]).astype("float32"))
c = tvm.nd.array(np.zeros([10,10]).astype("float32"))

In [6]:
f(10,10,10,a,b)

<tvm.nd.NDArray shape=(10, 10), cpu(0)>
array([[0.80510855, 0.6177056 , 0.5603828 , 0.9102205 , 0.5576379 ,
        0.42637053, 0.19185884, 0.30839843, 0.5352756 , 0.3780563 ],
       [0.47429246, 0.05785687, 0.21392788, 0.75180084, 0.66964394,
        0.6739003 , 0.3620569 , 0.4983391 , 0.13864484, 0.48454037],
       [0.14078975, 0.16740347, 0.03652104, 0.02735858, 0.26019773,
        0.9334278 , 0.18240897, 0.45085183, 0.15235758, 0.974835  ],
       [0.22637542, 0.9206642 , 0.8287186 , 0.39308718, 0.8644168 ,
        0.44020545, 0.14770989, 0.981486  , 0.23660518, 0.48908222],
       [0.3308175 , 0.483518  , 0.640099  , 0.2295285 , 0.04099036,
        0.854106  , 0.9815058 , 0.08239236, 0.7965097 , 0.20190316],
       [0.28011656, 0.79725415, 0.21851724, 0.2919901 , 0.9917293 ,
        0.19309391, 0.58975863, 0.8074249 , 0.34479624, 0.7550865 ],
       [0.16571039, 0.18028381, 0.6049665 , 0.00488633, 0.39242247,
        0.1739541 , 0.45917198, 0.5954561 , 0.488894  , 0.7927062 ],
 

In [12]:
b

<tvm.nd.NDArray shape=(10, 10), cpu(0)>
array([[0.63885516, 0.76217985, 0.66781217, 0.42167827, 0.77606165,
        0.87899595, 0.13954517, 0.19494462, 0.5566105 , 0.1356776 ],
       [0.12344714, 0.11644306, 0.7667359 , 0.49603465, 0.24494156,
        0.67921495, 0.88124216, 0.34656146, 0.39182344, 0.13951723],
       [0.11136579, 0.9714099 , 0.84681046, 0.5513978 , 0.49912006,
        0.5367322 , 0.26370287, 0.8824267 , 0.488377  , 0.93511444],
       [0.87035537, 0.9183424 , 0.23424606, 0.5474942 , 0.48502746,
        0.30551544, 0.6326374 , 0.8611012 , 0.2212995 , 0.20923267],
       [0.60483515, 0.5984601 , 0.47096726, 0.46076012, 0.29935098,
        0.93612   , 0.7337843 , 0.77958095, 0.0087426 , 0.36821342],
       [0.1443562 , 0.6524004 , 0.819598  , 0.6272308 , 0.80844647,
        0.01007976, 0.06309981, 0.51160645, 0.06373317, 0.12920205],
       [0.52035564, 0.14926699, 0.6180188 , 0.8056257 , 0.50174356,
        0.2309184 , 0.02239374, 0.51595944, 0.8795373 , 0.7720912 ],
 

In [13]:
c

<tvm.nd.NDArray shape=(10, 10), cpu(0)>
array([[2.986868  , 2.0171003 , 3.1109884 , 2.8828335 , 2.6310985 ,
        2.257384  , 2.8951244 , 3.122688  , 1.6737014 , 2.3704882 ],
       [2.209608  , 1.8376703 , 2.4566917 , 2.2485714 , 2.4337506 ,
        1.6505035 , 2.2462072 , 2.5550137 , 1.3725843 , 1.2533975 ],
       [1.6062827 , 1.2888751 , 2.2871149 , 1.4524959 , 2.0124393 ,
        0.77422494, 1.61233   , 1.4519949 , 0.85628504, 0.7276125 ],
       [3.0332992 , 2.1075256 , 3.9837291 , 3.0989025 , 2.9858582 ,
        2.85209   , 2.7148666 , 2.4105716 , 1.2390255 , 2.3046348 ],
       [2.510458  , 2.5257018 , 2.563356  , 2.1987913 , 2.5742476 ,
        1.2544774 , 1.963557  , 2.1633842 , 1.3640802 , 1.8673389 ],
       [2.5290978 , 1.853854  , 3.4928303 , 3.029682  , 2.7048912 ,
        2.2963445 , 2.4932914 , 2.2492194 , 1.3572698 , 1.9441772 ],
       [1.6666194 , 1.6351556 , 2.6243699 , 1.7749462 , 1.8729037 ,
        1.4266297 , 2.0875764 , 1.4027468 , 1.0117218 , 1.4446672 ],
 

In [1]:
from tvm import te
import tvm

def packb(K, N, B):
    f = tvm._ffi.get_global_func("tvm.contrib.mlas.gemm_packb_size")
    packb_size = f(N, K)
    arr_size = packb_size / 4
    return te.extern(
        (int(arr_size),),
        [B],
        lambda ins, outs: tvm.tir.call_packed(
            "tvm.contrib.mlas.gemm_packb",
            N, K, N,
            ins[0],
            outs[0],
        ),
        dtype='float32'
    )

In [2]:
B = te.placeholder([100, 100], dtype='float32')

In [3]:
packed = packb(100, 100, B)

In [5]:
s = te.create_schedule([packed.op])

In [8]:
mod = tvm.build(s, [B, packed])

In [22]:
mod(a, b)

In [23]:
a

<tvm.nd.NDArray shape=(100, 100), cpu(0)>
array([[0.81536674, 0.79854214, 0.99308944, ..., 0.28967544, 0.7355457 ,
        0.4344557 ],
       [0.8255604 , 0.4155204 , 0.9251404 , ..., 0.62362844, 0.9411293 ,
        0.59831357],
       [0.73155415, 0.41148418, 0.13224329, ..., 0.49938843, 0.19183408,
        0.7397192 ],
       ...,
       [0.13557947, 0.98957497, 0.20982774, ..., 0.3623292 , 0.15731752,
        0.65456605],
       [0.5667103 , 0.04093495, 0.7424174 , ..., 0.7410906 , 0.3031614 ,
        0.02527095],
       [0.97589916, 0.83508277, 0.2895802 , ..., 0.3535886 , 0.8083846 ,
        0.48452786]], dtype=float32)

In [24]:
b

<tvm.nd.NDArray shape=(11200,), cpu(0)>
array([0.81536674, 0.8255604 , 0.73155415, ..., 0.        , 0.        ,
       0.        ], dtype=float32)

In [5]:
from tvm import relay
import numpy as np
import tvm

In [59]:
A = relay.var(name='A', shape=[1, 100, 200])
B = relay.var(name='B', shape=[1, 100, 200])

In [60]:
C = relay.

In [61]:
C = relay.reshape(B, [-1])

In [62]:
f = relay.Function([], C)
new_f = run_opt_pass(f, relay.transform.FoldConstant())

In [63]:
mod = tvm.IRModule({"main": new_f})

In [72]:
a.data

<tvm.nd.NDArray shape=(10, 10), cpu(0)>
array([[0.06465196, 0.13767472, 0.4391983 , 0.20785977, 0.19488935,
        0.8125772 , 0.9256632 , 0.29711232, 0.41217148, 0.5142895 ],
       [0.43163627, 0.50280017, 0.6399901 , 0.13974953, 0.65293217,
        0.28123626, 0.35156855, 0.15876971, 0.81641793, 0.3701084 ],
       [0.9574488 , 0.5687055 , 0.27471197, 0.7404051 , 0.12457157,
        0.87549037, 0.2739537 , 0.41783926, 0.8043953 , 0.39487416],
       [0.5336113 , 0.6877586 , 0.18924832, 0.7805741 , 0.7573533 ,
        0.14872167, 0.71668273, 0.44548893, 0.7032608 , 0.06775627],
       [0.8373858 , 0.25297388, 0.02372047, 0.2913654 , 0.29016575,
        0.50660807, 0.26232007, 0.34525457, 0.57314426, 0.44166517],
       [0.17031439, 0.15266502, 0.20940718, 0.36861548, 0.40896717,
        0.7730219 , 0.2877399 , 0.79967463, 0.4069027 , 0.8654268 ],
       [0.6404122 , 0.58320147, 0.25162002, 0.33019975, 0.8156568 ,
        0.86584705, 0.12401273, 0.57544214, 0.60125154, 0.78341746],
 

In [64]:
dev = tvm.cpu()
target = "llvm"
executable = relay.vm.compile(mod, target)

In [65]:
 des_vm = tvm.runtime.vm.VirtualMachine(executable, dev)

In [73]:
relay.Function?

In [66]:
b = des_vm.run()

In [67]:
b

<tvm.nd.NDArray shape=(160,), cpu(0)>
array([0.06465196, 0.13767472, 0.4391983 , 0.20785977, 0.19488935,
       0.8125772 , 0.9256632 , 0.29711232, 0.41217148, 0.5142895 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.43163627, 0.50280017, 0.6399901 , 0.13974953,
       0.65293217, 0.28123626, 0.35156855, 0.15876971, 0.81641793,
       0.3701084 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.9574488 , 0.5687055 , 0.27471197,
       0.7404051 , 0.12457157, 0.87549037, 0.2739537 , 0.41783926,
       0.8043953 , 0.39487416, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.5336113 , 0.6877586 ,
       0.18924832, 0.7805741 , 0.7573533 , 0.14872167, 0.71668273,
       0.44548893, 0.7032608 , 0.06775627, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.8373858 ,
       0.25297388, 0.02372047, 0.2913654 , 0.29016575, 0.50660807,
       0.26232007, 0.345

In [31]:
def run_opt_pass(expr, opt_pass):
    assert isinstance(opt_pass, tvm.transform.Pass)

    mod = tvm.IRModule.from_expr(expr)
    mod = relay.transform.InferType()(mod)
    mod = opt_pass(mod)
    entry = mod["main"]
    return entry if isinstance(expr, relay.Function) else entry.body

Constant([[0.06465196 0.13767472 0.4391983  0.20785977 0.19488935 0.8125772
  0.9256632  0.29711232 0.41217148 0.5142895 ]
 [0.43163627 0.50280017 0.6399901  0.13974953 0.65293217 0.28123626
  0.35156855 0.15876971 0.81641793 0.3701084 ]
 [0.9574488  0.5687055  0.27471197 0.7404051  0.12457157 0.87549037
  0.2739537  0.41783926 0.8043953  0.39487416]
 [0.5336113  0.6877586  0.18924832 0.7805741  0.7573533  0.14872167
  0.71668273 0.44548893 0.7032608  0.06775627]
 [0.8373858  0.25297388 0.02372047 0.2913654  0.29016575 0.50660807
  0.26232007 0.34525457 0.57314426 0.44166517]
 [0.17031439 0.15266502 0.20940718 0.36861548 0.40896717 0.7730219
  0.2877399  0.79967463 0.4069027  0.8654268 ]
 [0.6404122  0.58320147 0.25162002 0.33019975 0.8156568  0.86584705
  0.12401273 0.57544214 0.60125154 0.78341746]
 [0.13160045 0.41837218 0.9593023  0.3207356  0.19007893 0.3369554
  0.16157986 0.30925828 0.8486106  0.71999574]
 [0.6212595  0.19669153 0.46251094 0.44341126 0.06801451 0.6466241
  0.581

In [1]:
from tvm import topi
from tvm import te

In [2]:
A = te.placeholder([1,10,20],dtype='float32')
B = te.placeholder([1,10,20],dtype='float32')

In [3]:
C = topi.x86.batch_matmul(A, B)

In [4]:
s = te.create_schedule([C.op])

In [6]:
mod = tvm.build(s, [A,B,C])

In [11]:
a = tvm.nd.array(np.random.random([1,10,20]).astype("float32"))
b = tvm.nd.array(np.random.random([1,10,20]).astype("float32"))
c = tvm.nd.array(np.random.random([1,10,10]).astype("float32"))

In [12]:
mod(a,b,c)

In [13]:
c

<tvm.nd.NDArray shape=(1, 10, 10), cpu(0)>
array([[[5.9070053, 5.6469536, 5.4860535, 4.7519937, 5.9405446,
         4.47134  , 3.8897479, 5.026016 , 6.2607384, 4.9040933],
        [6.524731 , 5.2883015, 4.4011636, 4.7517743, 4.661119 ,
         4.8948345, 3.917539 , 4.4769382, 5.4227366, 4.902374 ],
        [5.153442 , 5.1841073, 4.843999 , 4.3979635, 4.7466826,
         3.9900556, 3.823713 , 4.7899413, 5.431776 , 3.844094 ],
        [6.141867 , 5.804394 , 5.203883 , 5.1674848, 5.6195426,
         4.713909 , 3.5946338, 5.483607 , 5.758065 , 5.1385465],
        [5.766115 , 5.8301716, 5.5333853, 4.917551 , 6.01125  ,
         4.6886873, 3.9715457, 4.861796 , 6.612072 , 4.6031194],
        [5.7954144, 4.643298 , 4.2163153, 4.4090686, 4.787347 ,
         3.4580421, 3.1607764, 4.3638706, 5.169836 , 4.3452144],
        [6.530846 , 6.5930905, 5.106441 , 5.956667 , 6.1194   ,
         4.961995 , 3.9514396, 5.2418504, 6.046749 , 4.713728 ],
        [6.3811584, 5.961465 , 5.552847 , 5.1700425, 5

In [15]:
A = a.asnumpy().reshape([10,20])

In [16]:
B = b.asnumpy().reshape([10,20])

In [18]:
np.dot(A, B.T)

array([[5.9070053, 5.6469536, 5.4860535, 4.7519937, 5.9405446, 4.47134  ,
        3.8897479, 5.026016 , 6.2607384, 4.9040933],
       [6.524731 , 5.2883015, 4.4011636, 4.7517743, 4.661119 , 4.8948345,
        3.917539 , 4.4769382, 5.4227366, 4.902374 ],
       [5.153442 , 5.1841073, 4.843999 , 4.3979635, 4.7466826, 3.9900556,
        3.823713 , 4.7899413, 5.431776 , 3.844094 ],
       [6.141867 , 5.804394 , 5.203883 , 5.1674848, 5.6195426, 4.713909 ,
        3.5946338, 5.483607 , 5.758065 , 5.1385465],
       [5.766115 , 5.8301716, 5.5333853, 4.917551 , 6.01125  , 4.6886873,
        3.9715457, 4.861796 , 6.612072 , 4.6031194],
       [5.7954144, 4.643298 , 4.2163153, 4.4090686, 4.787347 , 3.4580421,
        3.1607764, 4.3638706, 5.169836 , 4.3452144],
       [6.530846 , 6.5930905, 5.106441 , 5.956667 , 6.1194   , 4.961995 ,
        3.9514396, 5.2418504, 6.046749 , 4.713728 ],
       [6.3811584, 5.961465 , 5.552847 , 5.1700425, 5.817587 , 3.9778585,
        4.6880364, 4.882497 , 5.92080