In [2]:
import tvm
import numpy as np

In [6]:
f = tvm._ffi.get_global_func("tvm.contrib.mlas.sgemm")

In [9]:
a = tvm.nd.array(np.random.random([10,10]).astype("float32"))
b = tvm.nd.array(np.random.random([10,10]).astype("float32"))
c = tvm.nd.array(np.zeros([10,10]).astype("float32"))

In [10]:
f(10, 10, 10, a, b, c)

In [11]:
a

<tvm.nd.NDArray shape=(10, 10), cpu(0)>
array([[0.80510855, 0.6177056 , 0.5603828 , 0.9102205 , 0.5576379 ,
        0.42637053, 0.19185884, 0.30839843, 0.5352756 , 0.3780563 ],
       [0.47429246, 0.05785687, 0.21392788, 0.75180084, 0.66964394,
        0.6739003 , 0.3620569 , 0.4983391 , 0.13864484, 0.48454037],
       [0.14078975, 0.16740347, 0.03652104, 0.02735858, 0.26019773,
        0.9334278 , 0.18240897, 0.45085183, 0.15235758, 0.974835  ],
       [0.22637542, 0.9206642 , 0.8287186 , 0.39308718, 0.8644168 ,
        0.44020545, 0.14770989, 0.981486  , 0.23660518, 0.48908222],
       [0.3308175 , 0.483518  , 0.640099  , 0.2295285 , 0.04099036,
        0.854106  , 0.9815058 , 0.08239236, 0.7965097 , 0.20190316],
       [0.28011656, 0.79725415, 0.21851724, 0.2919901 , 0.9917293 ,
        0.19309391, 0.58975863, 0.8074249 , 0.34479624, 0.7550865 ],
       [0.16571039, 0.18028381, 0.6049665 , 0.00488633, 0.39242247,
        0.1739541 , 0.45917198, 0.5954561 , 0.488894  , 0.7927062 ],
 

In [12]:
b

<tvm.nd.NDArray shape=(10, 10), cpu(0)>
array([[0.63885516, 0.76217985, 0.66781217, 0.42167827, 0.77606165,
        0.87899595, 0.13954517, 0.19494462, 0.5566105 , 0.1356776 ],
       [0.12344714, 0.11644306, 0.7667359 , 0.49603465, 0.24494156,
        0.67921495, 0.88124216, 0.34656146, 0.39182344, 0.13951723],
       [0.11136579, 0.9714099 , 0.84681046, 0.5513978 , 0.49912006,
        0.5367322 , 0.26370287, 0.8824267 , 0.488377  , 0.93511444],
       [0.87035537, 0.9183424 , 0.23424606, 0.5474942 , 0.48502746,
        0.30551544, 0.6326374 , 0.8611012 , 0.2212995 , 0.20923267],
       [0.60483515, 0.5984601 , 0.47096726, 0.46076012, 0.29935098,
        0.93612   , 0.7337843 , 0.77958095, 0.0087426 , 0.36821342],
       [0.1443562 , 0.6524004 , 0.819598  , 0.6272308 , 0.80844647,
        0.01007976, 0.06309981, 0.51160645, 0.06373317, 0.12920205],
       [0.52035564, 0.14926699, 0.6180188 , 0.8056257 , 0.50174356,
        0.2309184 , 0.02239374, 0.51595944, 0.8795373 , 0.7720912 ],
 

In [13]:
c

<tvm.nd.NDArray shape=(10, 10), cpu(0)>
array([[2.986868  , 2.0171003 , 3.1109884 , 2.8828335 , 2.6310985 ,
        2.257384  , 2.8951244 , 3.122688  , 1.6737014 , 2.3704882 ],
       [2.209608  , 1.8376703 , 2.4566917 , 2.2485714 , 2.4337506 ,
        1.6505035 , 2.2462072 , 2.5550137 , 1.3725843 , 1.2533975 ],
       [1.6062827 , 1.2888751 , 2.2871149 , 1.4524959 , 2.0124393 ,
        0.77422494, 1.61233   , 1.4519949 , 0.85628504, 0.7276125 ],
       [3.0332992 , 2.1075256 , 3.9837291 , 3.0989025 , 2.9858582 ,
        2.85209   , 2.7148666 , 2.4105716 , 1.2390255 , 2.3046348 ],
       [2.510458  , 2.5257018 , 2.563356  , 2.1987913 , 2.5742476 ,
        1.2544774 , 1.963557  , 2.1633842 , 1.3640802 , 1.8673389 ],
       [2.5290978 , 1.853854  , 3.4928303 , 3.029682  , 2.7048912 ,
        2.2963445 , 2.4932914 , 2.2492194 , 1.3572698 , 1.9441772 ],
       [1.6666194 , 1.6351556 , 2.6243699 , 1.7749462 , 1.8729037 ,
        1.4266297 , 2.0875764 , 1.4027468 , 1.0117218 , 1.4446672 ],
 

array([[2.986868  , 2.0171003 , 3.1109884 , 2.8828335 , 2.6310985 ,
        2.257384  , 2.8951244 , 3.122688  , 1.6737014 , 2.3704882 ],
       [2.209608  , 1.8376703 , 2.4566917 , 2.2485714 , 2.4337506 ,
        1.6505035 , 2.2462072 , 2.5550137 , 1.3725843 , 1.2533975 ],
       [1.6062827 , 1.2888751 , 2.2871149 , 1.4524959 , 2.0124393 ,
        0.77422494, 1.61233   , 1.4519949 , 0.85628504, 0.7276125 ],
       [3.0332992 , 2.1075256 , 3.9837291 , 3.0989025 , 2.9858582 ,
        2.85209   , 2.7148666 , 2.4105716 , 1.2390255 , 2.3046348 ],
       [2.510458  , 2.5257018 , 2.563356  , 2.1987913 , 2.5742476 ,
        1.2544774 , 1.963557  , 2.1633842 , 1.3640802 , 1.8673389 ],
       [2.5290978 , 1.853854  , 3.4928303 , 3.029682  , 2.7048912 ,
        2.2963445 , 2.4932914 , 2.2492194 , 1.3572698 , 1.9441772 ],
       [1.6666194 , 1.6351556 , 2.6243699 , 1.7749462 , 1.8729037 ,
        1.4266297 , 2.0875764 , 1.4027468 , 1.0117218 , 1.4446672 ],
       [1.9058436 , 1.4950626 , 2.091113 